language: node_js
node_js:
- node
deploy:
  provider: s3
  access_key_id: AKIAJEZI54MGUVYQR64Q
  secret_access_key:
    secure: Jrbd9A4wBdUUWxlnOjMScxs/rrCfGDgfgS8d2MQPvoIKfgURqXBHPDO17mARrDlLYXg8fkKdKtxJarSEqi4oAmxoO36EEIsnMMXjKrWtEsymcZV/yZRq4Rrs/0NBvUIbBcgrnO1EpmLgsFuMFIpMdnWNeHR8tZtSoNIUbWKq4I6nSMtEMasmnMJc7OcU0z0VRTh/lJ9oWTB02TxWedq0XVIlicRFKZdlXL7+q0vFZSRXC9s2/Vi5wKF6tMMyjU22wQ84WdQHhcLZtBt5zdX4aa0sElDGgrwvcfrBL1C5qKXhrtgYZNR8h+e+fBcDgEOi5Nd9mC66jQtksx+i/qoXSwRQ6Sydky4Op4gAmkj3cVaXC4u4ydNHVlqNmKTYNy0Qlct32SnsA8mXMmjCxoJ3NgIzSj9rNvmpRFDP4PW0Jq1c95uHJAD9rxZb/7fv1bQV8yuqbw/qzTCvvaNLBG4fdie7oG3BkbDhGQ7thTyW9HhtHUIvjL+8fIzP2S6OVbQmGRp1MAQVYLMe9iT2cSV8ZZa7qbt6SY0khTFhk/Q29L9VN62GSXtvLdX1OH4Pt6q+OWBOo68ou/M/KgRlcWAFyG7vXMSoxFdFU1G1eFUSTGelwHvD646/mPnz1MuiBIkfQ3AjSe9kFeskf+V4uM5Z97wP5k17tF+4s30trETjx+I=
  bucket: webapp-pre.arabadjikova.com
  skip_cleanup: true
  acl: public_read
  local_dir: src
