language: node_js
node_js:
- node
deploy:
  provider: s3
  access_key_id: AKIAJEZI54MGUVYQR64Q
  secret_access_key:
    secure: KwkKWOWj37AwaOepSpPS9WnnGFXDqdH9glwCbfUnzQpkgnFmEwmkgkYIt1GjxFghktufW61/romFqvKBr8XZXRlQlQdj343s2ggP1bOD82CmhpobQBTIrBSvJ+3ixXU7ch24OfmRL8bDqebw2L1d6R7t5b76SzYvK6GJ6wzoNte5NoVlbYs4xpwOYXlopX6sSlKnrKESUi4t9G/TjSVSxn4D8YMzepkdoqcyt44fyLpNcZAhXkuDvX1p81a1V49vp1G5/txKsiQgSwm2LfrZIen6lcnqCYJTpGVuXDeDTEbfVy0BknvQGr7v8BJpKB290+XmQvkpAhNblik3Sl1zl+jxYV0NAF/YzBRqvkZsGWefw1fjqDGTABml+OG8seW9UmTqoFsN6SxCZIah3dfIr5oCI5w4m+hLAXL1w7BzxVBrGKi4unVdOR8UoZDoj7qTWT3KJ0V0tKpHeTVnYEVybxeQsLJxQFv69NbUtyrFBGiJSXnYIgTBL/ttLcT59tDPdbrTfEbW24bzQnj5GuTl3FzfVOQUNr0ZMF5cRf/enWKLsvtTZTzvv9+tbdB5336g99XftW9sTorBPNT4l5EbHx1oKpD51angh5H+TTY8Q060CAj5U4IJbPEafEo3bWVLjon16aO743m9GH3rHK9am7aAwrxOF6YyiI3LRSI8XB8=
  bucket: webapp-pre.arabadjikova.com
  skip_cleanup: true
  acl: public_read
  local_dir: src
